// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezlyhjpyaaznjehawpfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6bHloanB5YWF6bmplaGF3cGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTUyOTUsImV4cCI6MjA2Mzc3MTI5NX0.Z50K6Ham9MJSCWYVyO2NPsMws35tZNCEd0v5evIEs60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);